#!/bin/bash

# Simple rc/init script to start/stop HDS RAIDCOM (horcm)
# chkconfig: 2345 88 38

# $Id: horcm 9623 2016-06-17 18:48:18Z fma $

PATH=/bin:/usr/bin:/HORCM/usr/bin

INST=$(ls -1 /etc/horcm*.conf | sort -rV | head -1 | sed -e 's/^.*horcm//' -e 's/\.conf//')
if [ x$INST != x ] ; then
   case $1 in
   start)
      logger -t RAIDCOM "Starting HDS RAIDCOM..."
      /HORCM/usr/bin/horcmstart.sh $INST
      ;;
   stop)
      logger -t RAIDCOM "Stopping HDS RAIDCOM..."
      /HORCM/usr/bin/horcmshutdown.sh $INST
      ;;
   *)
      echo "$0 [start|stop]"
      exit 2
   esac
else
   logger -s -t RAIDCOM "No horcm{instance}.conf file found."
   exit 1
fi
