#!/usr/bin/env zsh

echo "Setting python to version 3.8, you may be prompted for password..."
sudo port select --set python python38
sudo port select --set python3 python38

echo "Setting pip to version 3.8..."
sudo port select --set pip pip38
sudo port select --set pip3 pip38
