#!/usr/bin/env zsh

echo "Switching python[3] to python39..."
sudo port select --set python python39
sudo port select --set python3 python39

echo "Switching pip[3] to pip39..."
sudo port select --set pip pip39
sudo port select --set pip3 pip39

vir_dir=$HOME/venv_python39
if [ -d $vir_dir ]
then
   echo "Upgrading ${vir_dir} with --copies venv_python39..."
   python -m venv --upgrade --upgrade-deps --copies $vir_dir
fi
