#!/usr/bin/env zsh

echo "Switching python[3] to python311..."
sudo port select --set python python311
sudo port select --set python3 python311

echo "Switching pip[3] to pip311..."
sudo port select --set pip pip311
sudo port select --set pip3 pip311

#echo "Activating other py311-related package(s)..."
#sudo port select --set pygments py311-pygments

vir_dir=$HOME/venv_python311
if [ -d $vir_dir ]
then
   echo "Upgrading ${vir_dir} with --copies venv_python311..."
   python -m venv --upgrade --upgrade-deps --copies $vir_dir
fi
